apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cityosjarvis.fullname" . }}
  labels:
    {{- include "cityosjarvis.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.env | where "name" "LOG_LEVEL" | first | default (dict "value" "INFO") | pluck "value" | first | quote }}
  ENABLE_TTS: {{ .Values.env | where "name" "ENABLE_TTS" | first | default (dict "value" "true") | pluck "value" | first | quote }}
  ENABLE_AUDIT: {{ .Values.env | where "name" "ENABLE_AUDIT" | first | default (dict "value" "true") | pluck "value" | first | quote }}
